In [ ]:
import numpy as np

**Wprowadzenie**

Dzisiejsze zadanie polega na rozwiązaniu układu równań

* $4 x- 3 y + z = -10$
* $2x + y + 3z = 0$
* $-x + 2y - 5z = 17$

metodą eliminacji Gaussa. Algorytm ten wykorzystuje trzy podstawowe operacje, które pozwalają przekształcić układ równań do postaci schodkowej, w której łatwo jest odczytać rozwiązanie. Te operacje to:
* Pomnożenie wiersza macierzy rozszerzonej przez liczbę różną od zera.
* Zamiana dwóch wierszy miejscami w macierzy rozszerzonej.
* Kombinacja liniowa, tzn. do wiersza $i$ dodajemy wiersz $j$ pomnożony przez liczbę różną od zera.

**Zad. 1.** Zapisz powyższy układ równań w postaci $A \vec{x} = \vec{b}$, gdzie $A$ jest macierzą współczynników, $\vec{x}$ wektorem złożonym z niewiadomych, a $\vec{b}$ wektorem wyrazów wolnych. **Wskazówka 1**: użyj funkcji `np.array`. **Wskazówka 2** Współczynniki w powyższym układzie równań są typu *int* (całkowitego), ale przekształć je do typu $float$ (zmiennoprzecinkowy).

In [ ]:
A = np.array(### TWÓJ KOD TUTAJ ###, dtype = ### TWÓJ KOD TUTAJ ###)
b = np.array(### TWÓJ KOD TUTAJ ###, dtype = ### TWÓJ KOD TUTAJ ###)

**Zad. 2** Zbuduj macierz rozszerzoną z obiektów $A$ i $b$. **Wskazówka**: użyj funkcji `np.hstack` oraz funkcji `np.reshape`, żeby zrobić wektor kolumnowy z $\vec{b}$

In [ ]:
A_ex = ### TWÓJ KOD TUTAJ ###
A_ex

**Zad. 3**. Zdefiniuj funkcję `pomnóż_wiersz` (pierwsza z operacji elementarnych w algorytmie eliminacji Gaussa), która pobiera trzy argumenty:
* macierz,
* numer (indeks) wiersza, który chcemy pomnożyć,
* liczbę przez którą chcemy ten wiersz pomnożyć

i zwraca macierz, której *i*-ty wiersz jest pomnożony przez żądaną liczbę.

In [ ]:
def pomnoz_wiersz(macierz, nr_wiersza, mnoznik):
  macierz_nowa = macierz.copy()
  ### TWÓJ KOD TUTAJ ###
  return macierz_nowa


**Zad. 4**. Zdefiniuj funkcję `zamień_wiersze` (druga z operacji elementarnych w algorytmie eliminacji Gaussa), która pobiera trzy argumenty:
* macierz,
* numer (indeks) pierwszego wiersza, który chcemy zamienić,
* numer (indeks) drugiego wiersza, który chcemy zamienić

i zwraca macierz, w której wiersze są zamienione miejscami.

In [ ]:
def zamien_wiersze(macierz, wiersz_1, wiersz_2):
  macierz_nowa = macierz.copy()
  ### TWÓJ KOD TUTAJ ###
  ### TWÓJ KOD TUTAJ ###
  ### TWÓJ KOD TUTAJ ###
  return macierz_nowa

**Zad. 5**. Zdefiniuj funkcję `kombinacja_liniowa` (trzecia z operacji elementarnych w algorytmie eliminacji Gaussa), która pobiera cztery argumenty:
* macierz,
* numer (indeks) wiersza, który chcemy pomnożyć i dodać do drugiego wiersza,
* numer (indeks) drugiego wiersza, do którego chcemy dodać pierwszy wiersz pomnożony przez liczbę
* liczbę, przez którą chcemy pomnożyć pierwszy wiersz

i zwraca macierz, w której do drugiego wiersza jest dodany pierwszy wiersz pomnożony przez liczbę.

In [ ]:
def kombinacja_liniowa(macierz, wiersz_1, wiersz_2, mnoznik):
  macierz_nowa = macierz.copy()
  ### TWÓJ KOD TUTAJ ###
  return macierz_nowa

**Zad.6.** Wykorzystując zdefiniowane operacje elementarne, rozwiąż podany układ równań. **Wskazówka**: spróbuj to najpierw rozwiązać na kartce. Wynikiem końcowym powinna być następująca macierz rozszerzona

In [ ]:
[[ 1.  0.  0.  1.]
 [ 0.  1.  0.  4.]
 [-0. -0.  1. -2.]]

In [ ]:
### TWÓJ KOD TUTAJ ###

**Zad. 7.** Sprawdź za pomocą funkcji `np.linalg.solve`, jakie powinno być rozwiązanie powyższego układu i porównaj ze swoim wynikiem.

In [ ]:
### TWÓJ KOD TUTAJ ###